# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: Build Release

permissions: 
  contents: write

on:
  push:
    tags:
      - 'v*'

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: "Checkout Project"
      uses: actions/checkout@v4

    - name: "Checkout vcpkg"
      uses: actions/checkout@v4
      with:
        repository: "Microsoft/vcpkg"
        path: "vcpkg"

    - name: Bootstrap vcpkg
      run: "${{github.workspace}}/vcpkg/bootstrap-vcpkg.bat"

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build Release
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Create Release
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh release create ${{ github.ref_name }} \
          --generate-notes \
          --title "${{ github.ref_name }}" \
          ${{github.workspace}}/build/Release/media_monitor_cli.exe

    #- name: Test
    #  working-directory: ${{github.workspace}}/build
    #  # Execute tests defined by the CMake configuration.
    #  # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
    #  run: ctest -C ${{env.BUILD_TYPE}}

